default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: reading_list_development

test:
  <<: *default
  database: reading_list_test

production:
  <<: *default
  database: reading_list_production
  username: reading_list
  password: <%= ENV['READING_LIST_DATABASE_PASSWORD'] %>
